# Generated by Django 3.2.7 on 2021-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('studentnum', models.CharField(max_length=50, verbose_name='STUDENTNUM')),
                ('tel', models.CharField(max_length=50, verbose_name='MOBILE')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='EMAIL')),
                ('lecture', models.CharField(max_length=100, verbose_name='LECTURE')),
                ('professor', models.CharField(max_length=100, verbose_name='PROFESSOR')),
            ],
            options={
                'ordering': ('lecture', 'name'),
            },
        ),
    ]
