# Generated by Django 3.2.7 on 2021-11-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namecard', '0002_namecard_tbl_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namecard_tbl',
            name='birth_dt',
        ),
    ]
